### ISSUE TITLE
Force HTTPS button not working

### ISSUE THREAD

**Issue by kojuharov** [Rarst/sg-cachepress#26] opened 2017-09-26 14:33 UTC
The Force HTTPS button in SuperCacher -> HTTPS Config button is not working.

There are two scenarios in which it should work and it does not. Both tested with the subdomain installation. First one:

1. Go to Network Admin -> Sites and pick a random website. For example kojuharov.sgmstest-subdomain.com.
2. Click Edit for that website and in the Settings tab, **disable** the "Disallow HTTPS Configuration" option.
3. This will make the menu SuperCacher -> HTTPS Config appear in the Dashboard of that particular website.
4. Access it and try to click the Force HTTPS button - it does not work

Next scenario:
1. Go to Network Admin -> Sites and pick a random website. For example kojuharov.sgmstest-subdomain.com.
2. Click Edit for that website and in the Settings tab, **disable** the "Disallow HTTPS Configuration" option.
3. Now, **enable** the option Force HTTPS for that website. This adds .htaccess rules to redirect to HTTPS the website.
4. Go to the Dashboard of that website -> SuperCacher -> HTTPS Config. The button Force HTTPS is off, but you already Forced HTTPS from the Network Admin Settings menu for that website, meaning it does not check if HTTPS is already enabled properly.

**Comment by Rarst** [comment] 2017-09-28 11:21
I've found _one_ problem with logic check and pushed a fix.

Not confident this resolves everything described, could you please update on live server and retest there? :)

**Comment by kojuharov** [comment] 2017-09-28 11:33
I tested the button but it still does not work correctly. Now, when you click the button, it makes the POST request to force HTTPS on the website, but when the page refreshes - the button still shows the option as disabled.

You can test on https://sgmstest-subdomain.com/wp-admin/admin.php?page=ssl

**Comment by Rarst** [comment] 2017-10-02 07:51
Hunted down another place that needed multisite check and fixed.

This seems to get toggling option both from site's and network admin's settings for me.

**Comment by kojuharov** [comment] 2017-10-02 08:52
Yes, everything appears to be working normally with the Force HTTPS button now.

**Comment by kojuharov** [comment] 2017-10-02 11:17
Just finished testing and there is another problem with the Force HTTPS button and it appears only on the mapped domains MU installation.

The problem is that when you log in the dashboard of a subsite - sgmstest-mapped.com and then go to the Force HTTPS section - https://sgmstest-mapped.com/wp-admin/admin.php?page=ssl, then you try and disable the Force HTTPS option you are logged out and when you log back in - the option is still enabled.

Tested on all PHP versions and the problem persists. Also it is only present on the mapped domains installation and not on any of other MU setups.

**Comment by Rarst** [comment] 2017-10-04 09:20
Here is how far I got so far:

1. This is specific to MU Domain Mapping plugin
2. If admin is accessed with httpS then plugin overrides `siteurl` option to be httpS, _regardless_ of what protocol is stored in database
3. This throws of if Force HTTPS is enabled check, since the values checked are now from override and not database originals
4. When option is updated to http after relogin _something_ forces redirect back to httpS on login and we are back to square one (protocol in db options ignored)

**Comment by Rarst** [comment] 2017-10-04 11:16
Ok, the issues seems to be caused by Domain Mapping making Optimizer think output buffering is necessary and changing non-secure login form to point to _secure_ submit destination, which routes login back into secure admin right after Force HTTPs was disabled.

**Comment by Rarst** [comment] 2017-10-04 15:55
I had been able to reproduce the cookie error _without_ SG Optimizer enabled altogether. Just by logging out and trying to re-login into site.

At this point it looks like a breakage in Domain Mapping plugin, which our use case just _surfaces_ but not _causes_.

**Comment by Rarst** [comment] 2017-10-22 18:50
Ok, I wasn't making progress so I went all out and rebuilt everything from scratch locally — domain mapped multisite install, SSL, certificates, and everything.

I _definitely_ can get this error without SG Optimizer involved, though not very consistently:

1. Log into httpS version of mapped domain
2. Log out
3. Go to http version of login
4. Try to login = usually cookies error at this point

Sometimes error comes up repeatedly, sometimes another login attempt works.

At this point I am not sure if we can possibly do something about this at all within scope of the plugin. Way out of my depth on multisite and servers.

**Closed as completed** 2017-10-25 13:32 UTC
Labels: bug
